name: s-search
base: core22
version: git
summary: Open a web search in your terminal. 
description: |
  Web search from the terminal. Just opens in your browser.

grade: stable
confinement: strict
source: https://github.com/zquestz/s
issues: https://github.com/zquestz/s/issues
contact: https://github.com/zquestz/s
license: MIT

architectures:
  - build-on: amd64
  - build-on: s390x
  - build-on: armhf
  - build-on: arm64
  - build-on: ppc64el


parts:
  s:
    plugin: go
    source: https://github.com/zquestz/s
    source-type: git
    build-packages:
      - gcc

apps:
  s-search:
    command: s
    plugs:
      - network
