name: s-search
base: core22
adopt-info: s-search
summary: Open a web search in your terminal. 
description: |
  Web search from the terminal. Just opens in your browser.

grade: stable
confinement: strict

source-code: https://github.com/zquestz/s
issues: https://github.com/zquestz/s/issues
contact: https://github.com/zquestz/s
license: MIT

architectures:
  - build-on: amd64
  - build-on: s390x
  - build-on: armhf
  - build-on: arm64
  - build-on: ppc64el

apps:
  s-search:
    command: bin/s
    plugs:
      - network

parts:
  s-search:
    source: https://github.com/zquestz/s
    source-type: git
    plugin: go    
    build-snaps:
      - go
      
    build-packages:
      - gcc      
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
